### PR TITLE
Support an optional second y-axis for datasets

### PR DESCRIPTION
**Pull request by jschmer**
This serves as a basis for discussion/improvement, there are probably lot's of possible tweaks to support such a feature.
Feel free to take this and modify as you wish.

With this change you can define the "yAxisGroup" property in a filter config and set it to 0 (left y-axis) or 1 (right y-axis).
```
{
	"name": "Test",
	"type": 3,
	"apid": "TEST",
	"ctid": "CTX",
	"payloadRegex": "^Hello (?<world>\w+)",
	"yAxisGroup": 1
}
```

### CODE REVIEW

**Comment by jschmer** [comment]
Ideally, it would also be possible to specify a "yAxisGroup" for every capture individually. Sounds like an addition to reportOptions settings that maps a "yAxisGroup" to a capture label.
Could in theory also support even more y axis (currently 2 for numbers, 1 for "states")

**Comment by jschmer** [comment]
Changed to include config into reportOptions:
```
{
	"name": "Test",
	"type": 3,
	"apid": "TEST",
	"ctid": "CTX",
	"payloadRegex": "^Data: (?<first>[0-9]+) (?<second>[0-9]+)",
	"reportOptions": {
		"axisMap": {
			"second": 1
		}
	},
}
```

**Comment by mbehr1** [comment]
thx! this is a really nice feature. will try it and have to think a bit about it, read charts doc,... -> weekend :-)

**Comment by mbehr1** [comment]
This approach doesn't quite scale to multiple reports in same report. E.g. if you open multiple reports. So I'd suggest to not use a static assignment but instead add the possibility of adding yAxes attributes to the reportOptions. E.g. like this:
```jsonc
{
	"name": "Test",
	"type": 3,
	"apid": "TEST",
	"ctid": "CTX",
	"payloadRegex": "^Data: (?<first>[0-9]+) (?<second>[0-9]+)",
	"reportOptions": {
                "yAxes":{ // config options matching chartjs Cartesian Axes
                   "second":{ // either dataSet name or * (or _)  as wildcard
                      "type": "linear", // or logarithmic or category, optional
                      "position": "right", // or left, optional
                      "ticks": {
                         "min": -20,
                         "max": 60
                      }
                   }
                }
	}
}
```
This way the axes can be autogenerated based on:
- does an axis with same options exist yet? 
   - yes: use it
   - no: create new one.

**Comment by mbehr1** [comment]
@jschmer if you don't mind I'll create a PR with the upper commented proposal?

**Comment by jschmer** [comment]
So if you have multiple filters with the same axis options it will essentially pack all datasets into one axis. If they are different it will generate a new axis automaticlly? That sound pretty neat, go ahead and ditch this PR if you have something better :)

**Comment by mbehr1** [comment]
yes, exactly. got it basically ready.

**Comment by mbehr1** [comment]
see PR#15. Will add 2nd commit with doc update. Tests/feedback would be highly appreciated.

**Comment by jschmer** [comment]
Better version implemented by #15

**Pull request closed without merging**
